require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true

# Layout
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "lib/dphil/cli_commands/*.rb"

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/ClassLength:
  Enabled: true
  Max: 250

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 30

Metrics/ModuleLength:
  Enabled: true
  Max: 250

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: false

# Naming
Naming/UncommunicativeMethodParamName:
  Enabled: false

# RSpect
RSpec/ContextWording:
  Enabled: false

# Style
Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true
