dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable; export PATH="$HOME/.cargo/bin:$PATH"
script: bundle exec rake spec SPEC_OPTS="--format p"
