---
- - :whitelist
  - ruby
  - &1
    :who: nomoon@phoebus.ca
    :why: Setup
    :versions: []
    :when: 2017-07-12 20:36:39.510096000 Z
- - :whitelist
  - MIT
  - *1
- - :whitelist
  - BSD
  - *1
- - :whitelist
  - SimplifiedBSD
  - *1
- - :whitelist
  - Apache2
  - *1
- - :whitelist
  - Unlicense
  - *1
- - :blacklist
  - GPLv2
  - :who: nomoon@phoebus.ca
    :why: Setup
    :versions: []
    :when: 2017-07-12 20:38:30.791451000 Z
- - :license
  - neatjson
  - MIT
  - :who: 
    :why: 
    :versions: []
    :when: 2017-07-13 04:56:50.867464000 Z
- - :license
  - unf
  - SimplifiedBSD
  - :who: 
    :why: 
    :versions: []
    :when: 2017-07-13 04:57:00.329471000 Z
- - :license
  - rouge
  - MIT
  - :who: 
    :why: 
    :versions: []
    :when: 2017-07-13 04:57:15.331415000 Z
- - :license
  - protocol
  - GPLv2
  - :who: 
    :why: 
    :versions: []
    :when: 2017-07-13 04:58:04.673212000 Z
